// id: the unique ID for each product - number
// name: the name of the product - string
// size: S or M or L - string

// ***IMPORTANT
// category: ["women", "men", "unisex", "kids", "s-a", "clothes", "products"]
// array of string: to choose and combine category

// ***IMPORTANT
// is_deal: having deal or not - boolean
// If is_deal = false, we will not show the sale price. If is_deal = true, we will show the sale price and the original price.

// original_price: the price before discount - number
// sale_price: the price after discount - number
// description: the details of the product - string
// image: the path of the image - string

const productList = [
  {
    id: 1,
    name: "Elegant Evening Dress",
    size: "M",
    category: ["women", "clothes", "products"],
    is_deal: true,
    original_price: 30.99,
    sale_price: 18.99,
    description: "Beautiful cream-colored dress with a thin layer of tulle on top.",
    image: "images/womens/1.png",
  }, 
  {
    id: 2,
    name: "Men's Classic Blue Jeans",
    size: "L",
    category: ["men", "clothes", "products"],
    is_deal: true,
    original_price: 39.99,
    sale_price: 29.99,
    description: "A classic pair of blue jeans for men.",
    image: "images/mens/men_jean.png",
  },
  {
    id: 3,
    name: "Adidas Running Shoes",
    size: "US 8 Women | US 6.5 Men",
    category: ["s-a", "unisex", "products", "trending"],
    is_deal: true,
    original_price: 130,
    sale_price: 100,
    description: "High-performance ruuning shoes for all athletes.",
    image: "images/s-a/1.png",
  },
  {
    id: 4,
    name: "Tulle Maxi Skirt",
    size: "S",
    category: ["women", "clothes", "products"],
    is_deal: true,
    original_price: 14.99,
    sale_price: 9.99,
    description: "A maxi-length skirt with an effortless silhouette.",
    image: "images/womens/2.png",
  },
  {
    id: 5,
    name: "Black Aviator Sunglasses",
    size: "One Size",
    category: ["s-a", "unisex", "products", "trending"],
    is_deal: false,
    original_price: 14.99,
    sale_price: 9.99,
    description: "Stylish sunglasses for unisex with UV protection.",
    image: "images/s-a/sunglass.png",
  },
  {
    id: 6,
    name: "Kid's Button Up Shirt",
    size: "M",
    category: ["kids", "clothes", "products"],
    is_deal: false,
    original_price: 9.99,
    sale_price: 7.99,
    description: "Kid's Plaid Button Up Shirt.",
    image: "images/kids/kid_shirt.png",
  },
  {
    id: 7,
    name: "Sport Shoes",
    size: "US 7.5 Women | US 6 Men",
    category: ["s-a", "unisex", "products"],
    is_deal: true,
    original_price: 39.99,
    sale_price: 19.99,
    description: "High-performance sport shoes for all.",
    image: "images/s-a/2.png",
  },
  {
    id: 8,
    name: "White Tshirt",
    size: "M",
    category: ["unisex", "clothes", "products", "trending"],
    is_deal: true,
    original_price: 19.99,
    sale_price: 9.99,
    description: "Good quality for all season.",
    image: "images/unisex/Tshirt.jpg",
  },
  {
    id: 9,
    name: "Rib Knit Bell Sleeve Crop Top",
    size: "S",
    category: ["women", "clothes", "products", "trending"],
    is_deal: true,
    original_price: 15.99,
    sale_price: 10.99,
    description: "Cute and classy top.",
    image: "images/womens/3.png",
  },
  {
    id: 10,
    name: "Curved Hem Drawstring Hoodie",
    size: "M",
    category: ["women", "clothes", "products", "trending"],
    is_deal: true,
    original_price: 30.99,
    sale_price: 16.99,
    description: "Grey cotton hoodie.",
    image: "images/womens/4.png",
  },
  {
    id: 11,
    name: "Daisy Bubble Dress",
    size: "S",
    category: ["women", "clothes", "products"],
    is_deal: true,
    original_price: 35.99,
    sale_price: 18.99,
    description: "Cute and comfy summer dress.",
    image: "images/womens/5.jpg",
  },
  {
    id: 12,
    name: "A-Line Midi Dress",
    size: "M",
    category: ["women", "clothes", "products"],
    is_deal: true,
    original_price: 32.99,
    sale_price: 16.99,
    description: "Beautiful, light green summer dress.",
    image: "images/womens/6.png",
  },
  {
    id: 13,
    name: "Oversized Grey Hoodie",
    size: "L",
    category: ["unisex", "clothes", "products", "trending"],
    is_deal: true,
    original_price: 35.99,
    sale_price: 20.99,
    description: "Soft and comfy hoodie.",
    image: "images/unisex/hoodie.jpg",
  },
  {
    id: 14,
    name: "Graphic Hoodie",
    size: "M",
    category: ["men", "unisex", "clothes", "products", "trending"],
    is_deal: true,
    original_price: 29.99,
    sale_price: 19.99,
    description: "A classic hoodie with graphics on the back.",
    image: "images/mens/men_hoodie.jpg",
  },
  {
    id: 15,
    name: "Men's Cargo Pants",
    size: "M",
    category: ["men", "clothes", "products", "trending"],
    is_deal: true,
    original_price: 29.99,
    sale_price: 19.99,
    description: "Classic Design Multi Flap Pockets Loose Wide Leg Cargo Pants,Men's Loose Fit Drawstring Cargo Pants",
    image: "images/mens/men_cargo_pants_2.jpg",
  },
  {
    id: 16,
    name: "Men's Print Jacket",
    size: "M",
    category: ["men", "clothes", "products", "trending"],
    is_deal: true,
    original_price: 45.25,
    sale_price: 30.25,
    description: "Trendy Letter Print Stand Collar Jacket, Men's Casual Jacket Coat Regular Fit Racing Pattern College Hipster Windbreaker For Spring Autumn",
    image: "images/mens/men_letter_print_jacket.jpg",
  },
  {
    id: 17,
    name: "Men's Solid Jip Up Jacket",
    size: "L",
    category: ["men", "clothes", "products"],
    is_deal: true,
    original_price: 36.25,
    sale_price: 20.25,
    description: "Classic Design Lightweight Jacket, Men's Casual Zip Up Stand Collar Zipper Pockets Jacket Coat For Spring Fall",
    image: "images/mens/men_solid_jipUp.jpg",
  },
  {
    id: 18,
    name: "Men's Plaid Shirt",
    size: "L",
    category: ["men", "clothes", "products"],
    is_deal: true,
    original_price: 26.25,
    sale_price: 15.25,
    description: "All-match Plaid Pattern Men's Casual Long Sleeve Lapel Shirt For Spring Fall, Special Gift For Men",
    image: "images/mens/men_plaid_shirt.jpg",
  },
  {
    id: 19,
    name: "Men's Plain Pants",
    size: "L",
    category: ["men", "clothes", "products", "trending"],
    is_deal: true,
    original_price: 26.25,
    sale_price: 15.25,
    description: "Regular Fit Chic Slacks, Men's Casual Vintage Style Solid Color Slightly Stretch Dress Pants For Spring Summer",
    image: "images/mens/men_plain_pants.jpg",
  },
  {
    id: 20,
    name: "Kid's Heart Sweater",
    size: "S",
    category: ["kids", "clothes", "products"],
    is_deal: true,
    original_price: 14.99,
    sale_price: 10.99,
    description: "Cute Pink Sweater With Hearts.",
    image: "images/kids/kid_heart_sweater.png",
  },
  {
    id: 21,
    name: "Kid's Pink Jacket",
    size: "M",
    category: ["kids", "clothes", "products"],
    is_deal: false,
    original_price: 25.99,
    sale_price: 20.99,
    description: "Cute Pink Bear Jacket.",
    image: "images/kids/kid_jacket.png",
  },
  {
    id: 22,
    name: "Kid's Jeans",
    size: "M",
    category: ["kids", "clothes", "products"],
    is_deal: true,
    original_price: 30.99,
    sale_price: 25.99,
    description: "Kid's Lightwash Jeans.",
    image: "images/kids/kid_jeans.jpeg",
  },
  {
    id: 23,
    name: "Kid's Tee",
    size: "S",
    category: ["kids", "clothes", "products"],
    is_deal: true,
    original_price: 30.99,
    sale_price: 25.99,
    description: "Kid's Tee with print.",
    image: "images/kids/kid_bud_shirt.png",
  },
  {
    id: 24,
    name: "Kid's Sweatshirt",
    size: "S",
    category: ["kids", "clothes", "products"],
    is_deal: false,
    original_price: 39.99,
    sale_price: 25.99,
    description: "Kid's Sycamore Fear of God Sweatshirt.",
    image: "images/kids/kids_FOG.jpeg",
  },
  {
    id: 25,
    name: "Kid's Sweatshirt",
    size: "M",
    category: ["kids", "clothes", "products"],
    is_deal: false,
    original_price: 30.99,
    sale_price: 30.99,
    description: "Kid's YEEZY x GAP blue hoodie.",
    image: "images/kids/kid_yeezy.png",
  },
  {
    id: 26,
    name: "Kid's Tee",
    size: "L",
    category: ["kids", "clothes", "products"],
    is_deal: true,
    original_price: 20.99,
    sale_price: 15.99,
    description: "Kid's Sanrio Tee.",
    image: "images/kids/kids_HK.png",
  },
  {
    id: 27,
    name: "Kid's Tee",
    size: "S",
    category: ["kids", "clothes", "products"],
    is_deal: true,
    original_price: 10.99,
    sale_price: 8.99,
    description: "Kid's Barbie Tee.",
    image: "images/kids/kid_barbie.png",
  },
  {
    id: 28,
    name: "Kid's Tee",
    size: "L",
    category: ["kids", "clothes", "products"],
    is_deal: true,
    original_price: 10.99,
    sale_price: 8.99,
    description: "Kid's Tee with Checkered Vans Logo.",
    image: "images/kids/kid_vans_shirt.png",
  },
  {
    id: 29,
    name: "White and black Sneakers",
    size: "US 10.5 Women | US 9 Men",
    category: ["s-a", "unisex", "products"],
    is_deal: false,
    original_price: 49.99,
    sale_price: 19.99,
    description: "Best walking sneakers with ultra thin layer of high abrasion rubber strategically placed on the outsole for targeted traction. Comfortable quality footwear light weight attractive design multi purpose.",
    image: "images/s-a/3.png",
  },
  {
    id: 30,
    name: "Browline Sunglasses",
    size: "One Size",
    category: ["s-a", "unisex", "products"],
    is_deal: false,
    original_price: 12.99,
    sale_price: 19.99,
    description: "Black browline sunglasses with gold trim",
    image: "images/s-a/sunglass_2.jpeg",
  },
  {
    id: 31,
    name: "Kid's Joggers",
    size: "L",
    category: ["kids", "clothes", "products"],
    is_deal: false,
    original_price: 20.99,
    sale_price: 15.99,
    description: "Kid's Light Gray Joggers.",
    image: "images/kids/kids_joggers.jpeg",
  },
  {
    id: 31,
    name: "Kid's Tracksuit",
    size: "M",
    category: ["kids", "clothes", "products"],
    is_deal: false,
    original_price: 20.99,
    sale_price: 15.99,
    description: "Kid's Red Tracksuit.",
    image: "images/kids/kids_tracksuit.png",
  },
  {
    id: 32,
    name: "Kid's Tracksuit",
    size: "L",
    category: ["kids", "clothes", "products"],
    is_deal: false,
    original_price: 25.99,
    sale_price: 15.99,
    description: "Kid's Black Tracksuit.",
    image: "images/kids/kids_blacktracksuit.png",
  },
  {
    id: 33,
    name: "Kid's Dress",
    size: "L",
    category: ["kids", "clothes", "products"],
    is_deal: false,
    original_price: 18.99,
    sale_price: 10.99,
    description: "Kid's Blue Dress.",
    image: "images/kids/kids_dress.jpeg",
  },
  {
    id: 34,
    name: "Women's UGG Tasman Slipper",
    size: "US 7 Women",
    category: ["women", "s-a", "products", "trending"],
    is_deal: true,
    original_price: 199.99,
    sale_price: 100.99,
    description: "Comfy tasman slippers for women in a rare goat color. Made of high quality fleece material for warm and cozy touch feeling, comfortable to wear.",
    image: "images/womens/7.jpg",
  },
  {
    id: 35,
    name: "Women's Faux Fur Bucket Hat",
    size: "One Size",
    category: ["women", "s-a", "products", "trending"],
    is_deal: false,
    original_price: 8.99,
    sale_price: 5.99,
    description: "A cute bear ear hat made fot the winter. The Faux Fur Bucket Hat is a fuzzy and cute hats that's fluffy, plush, and trendy.",
    image: "images/womens/8.jpg",
  }
];

export default productList;
